---
australiacentral:
  :name: australiacentral
  :description: Australia Central
australiacentral2:
  :name: australiacentral2
  :description: Australia Central 2
australiaeast:
  :name: australiaeast
  :description: Australia East
australiasoutheast:
  :name: australiasoutheast
  :description: Australia Southeast
brazilsouth:
  :name: brazilsouth
  :description: Brazil South
brazilsoutheast:
  :name: brazilsoutheast
  :description: Brazil Southeast
canadacentral:
  :name: canadacentral
  :description: Canada Central
canadaeast:
  :name: canadaeast
  :description: Canada East
centralindia:
  :name: centralindia
  :description: Central India
centralus:
  :name: centralus
  :description: Central US
centraluseuap:
  :name: centraluseuap
  :description: Central US EUAP
eastasia:
  :name: eastasia
  :description: East Asia
eastus:
  :name: eastus
  :description: East US
eastus2:
  :name: eastus2
  :description: East US 2
eastus2euap:
  :name: eastus2euap
  :description: East US 2 EUAP
francecentral:
  :name: francecentral
  :description: France Central
francesouth:
  :name: francesouth
  :description: France South
germanycentral:
  :name: germanycentral
  :description: Germany Central
germanynorth:
  :name: germanynorth
  :description: Germany North
germanynortheast:
  :name: germanynortheast
  :description: Germany Northeast
germanywestcentral:
  :name: germanywestcentral
  :description: Germany West Central
japaneast:
  :name: japaneast
  :description: Japan East
japanwest:
  :name: japanwest
  :description: Japan West
jioindiacentral:
  :name: jioindiacentral
  :description: Jio India Central
jioindiawest:
  :name: jioindiawest
  :description: Jio India West
koreacentral:
  :name: koreacentral
  :description: Korea Central
koreasouth:
  :name: koreasouth
  :description: Korea South
northcentralus:
  :name: northcentralus
  :description: North Central US
northeurope:
  :name: northeurope
  :description: North Europe
norwayeast:
  :name: norwayeast
  :description: Norway East
norwaywest:
  :name: norwaywest
  :description: Norway West
southafricanorth:
  :name: southafricanorth
  :description: South Africa North
southafricawest:
  :name: southafricawest
  :description: South Africa West
southcentralus:
  :name: southcentralus
  :description: South Central US
southeastasia:
  :name: southeastasia
  :description: Southeast Asia
southindia:
  :name: southindia
  :description: South India
swedencentral:
  :name: swedencentral
  :description: Sweden Central
switzerlandnorth:
  :name: switzerlandnorth
  :description: Switzerland North
switzerlandwest:
  :name: switzerlandwest
  :description: Switzerland West
uaecentral:
  :name: uaecentral
  :description: UAE Central
uaenorth:
  :name: uaenorth
  :description: UAE North
uksouth:
  :name: uksouth
  :description: UK South
ukwest:
  :name: ukwest
  :description: UK West
usgovarizona:
  :name: usgovarizona
  :description: US Gov Arizona
usgoviowa:
  :name: usgoviowa
  :description: US Gov Iowa
usgovtexas:
  :name: usgovtexas
  :description: US Gov Texas
usgovvirginia:
  :name: usgovvirginia
  :description: US Gov Virginia
westcentralus:
  :name: westcentralus
  :description: West Central US
westeurope:
  :name: westeurope
  :description: West Europe
westindia:
  :name: westindia
  :description: West India
westus:
  :name: westus
  :description: West US
westus2:
  :name: westus2
  :description: West US 2
westus3:
  :name: westus3
  :description: West US 3
